version: '3.8'

services:
  web:
    container_name: flask_app
    build: 
      context: ./app       
    ports:
      - "5000:5000"
    env_file:
      - .env               
    depends_on:
      - db                 

  db:
    container_name: mysql_db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  

volumes:
  db_data:
